export interface Location {
  slug: string
  name: string
  distance: string
  driveTime: string
  direction: string
  intro: string
  hausbesuche: boolean
  hausbesucheOnRequest?: boolean
}

export const locations: Location[] = [
  {
    slug: 'gross-bieberau',
    name: 'Groß-Bieberau',
    distance: '5 km',
    driveTime: '8 Minuten',
    direction: 'nördlich',
    intro: 'Groß-Bieberau liegt nur wenige Kilometer nördlich von Reinheim und ist eine der am nächsten gelegenen Gemeinden zu unserer Praxis. Als Einwohner von Groß-Bieberau erreichen Sie die Fortis Salutis Praxis in Reinheim in kürzester Zeit.',
    hausbesuche: true,
  },
  {
    slug: 'dieburg',
    name: 'Dieburg',
    distance: '10 km',
    driveTime: '13 Minuten',
    direction: 'nordöstlich',
    intro: 'Dieburg ist eine historische Stadt nordöstlich von Reinheim im Landkreis Darmstadt-Dieburg. Von Dieburg aus ist unsere Physiotherapiepraxis Fortis Salutis in Reinheim bequem und schnell erreichbar.',
    hausbesuche: true,
  },
  {
    slug: 'ober-ramstadt',
    name: 'Ober-Ramstadt',
    distance: '9 km',
    driveTime: '12 Minuten',
    direction: 'westlich',
    intro: 'Ober-Ramstadt liegt westlich von Reinheim am Fuße des Odenwalds. Die Gemeinde ist gut an das Straßennetz angebunden, sodass unsere Praxis in Reinheim für Patienten aus Ober-Ramstadt gut erreichbar ist.',
    hausbesuche: true,
  },
  {
    slug: 'darmstadt',
    name: 'Darmstadt',
    distance: '14 km',
    driveTime: '18 Minuten',
    direction: 'nordwestlich',
    intro: 'Darmstadt ist die nächste Großstadt zu Reinheim und liegt nordwestlich, nur etwa 14 km entfernt. Für Patienten aus Darmstadt ist unsere Privatpraxis Fortis Salutis in Reinheim eine attraktive Alternative zu städtischen Praxen.',
    hausbesuche: false,
  },
  {
    slug: 'rossdorf',
    name: 'Roßdorf',
    distance: '9 km',
    driveTime: '11 Minuten',
    direction: 'nördlich',
    intro: 'Roßdorf ist eine Gemeinde im Landkreis Darmstadt-Dieburg, nördlich von Reinheim gelegen. Patienten aus Roßdorf schätzen die persönliche und individuelle Behandlung in unserer Privatpraxis.',
    hausbesuche: true,
  },
  {
    slug: 'muehltal',
    name: 'Mühltal',
    distance: '10 km',
    driveTime: '13 Minuten',
    direction: 'westlich',
    intro: 'Mühltal liegt westlich von Reinheim an der Grenze zum Odenwald. Die idyllisch gelegene Gemeinde ist über gut ausgebaute Straßen mit Reinheim verbunden.',
    hausbesuche: true,
  },
  {
    slug: 'otzberg',
    name: 'Otzberg',
    distance: '7 km',
    driveTime: '10 Minuten',
    direction: 'östlich',
    intro: 'Otzberg liegt östlich von Reinheim und ist eine der nächsten Nachbargemeinden. Patienten aus Otzberg und seinen Ortsteilen erreichen unsere Praxis in Reinheim schnell und unkompliziert.',
    hausbesuche: true,
  },
  {
    slug: 'modautal',
    name: 'Modautal',
    distance: '8 km',
    driveTime: '12 Minuten',
    direction: 'südwestlich',
    intro: 'Modautal liegt südwestlich von Reinheim im Odenwald und umfasst mehrere malerische Ortsteile. Für Patienten aus dem Modautal bieten wir professionelle Physiotherapie in unserer Praxis in Reinheim.',
    hausbesuche: true,
  },
  {
    slug: 'fischbachtal',
    name: 'Fischbachtal',
    distance: '10 km',
    driveTime: '14 Minuten',
    direction: 'südwestlich',
    intro: 'Fischbachtal ist eine Gemeinde im südwestlichen Teil des Landkreises Darmstadt-Dieburg und liegt im ruhigen Odenwald. Von hier aus ist unsere Praxis in Reinheim gut erreichbar.',
    hausbesuche: true,
  },
  {
    slug: 'gross-zimmern',
    name: 'Groß-Zimmern',
    distance: '10 km',
    driveTime: '12 Minuten',
    direction: 'nördlich',
    intro: 'Groß-Zimmern liegt nördlich von Reinheim und ist eine der größeren Gemeinden in der Umgebung. Patienten aus Groß-Zimmern profitieren von der guten Anbindung an Reinheim.',
    hausbesuche: true,
  },
  {
    slug: 'babenhausen',
    name: 'Babenhausen',
    distance: '15 km',
    driveTime: '18 Minuten',
    direction: 'östlich',
    intro: 'Babenhausen liegt östlich von Reinheim am Rande des Landkreises Darmstadt-Dieburg. Patienten aus Babenhausen und Umgebung sind bei uns herzlich willkommen.',
    hausbesuche: false,
    hausbesucheOnRequest: true,
  },
  {
    slug: 'seeheim-jugenheim',
    name: 'Seeheim-Jugenheim',
    distance: '12 km',
    driveTime: '16 Minuten',
    direction: 'nordwestlich',
    intro: 'Seeheim-Jugenheim liegt westlich von Reinheim an der Bergstraße und ist für seine malerische Lage bekannt. Unsere Praxis in Reinheim ist von hier aus über die B26 gut erreichbar.',
    hausbesuche: false,
    hausbesucheOnRequest: true,
  },
  {
    slug: 'bickenbach',
    name: 'Bickenbach',
    distance: '11 km',
    driveTime: '14 Minuten',
    direction: 'westlich',
    intro: 'Bickenbach liegt westlich von Reinheim an der Bergstraße. Patienten aus Bickenbach schätzen die professionelle Betreuung in unserer Privatpraxis in Reinheim.',
    hausbesuche: false,
  },
  {
    slug: 'eppertshausen',
    name: 'Eppertshausen',
    distance: '11 km',
    driveTime: '14 Minuten',
    direction: 'nördlich',
    intro: 'Eppertshausen liegt nördlich von Reinheim und ist über gut ausgebaute Straßen erreichbar. Als Privatpraxis bieten wir Patienten aus Eppertshausen individuelle Physiotherapie auf höchstem Niveau.',
    hausbesuche: false,
    hausbesucheOnRequest: true,
  },
  {
    slug: 'spachbruecken',
    name: 'Spachbrücken',
    distance: '3 km',
    driveTime: '5 Minuten',
    direction: 'südlich',
    intro: 'Spachbrücken ist ein Ortsteil der Stadt Reinheim und liegt direkt vor unserer Haustür. Patienten aus Spachbrücken erreichen unsere Praxis in der Darmstädter Straße in nur wenigen Minuten.',
    hausbesuche: true,
  },
]
